/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridgeProxySol from "./BridgeProxy.sol";
export type { bridgeProxySol };
import type * as daiSol from "./DAI.sol";
export type { daiSol };
import type * as fdaiSol from "./FDAI.sol";
export type { fdaiSol };
import type * as fileBridgeSwapCore from "./file_bridge_swap_core";
export type { fileBridgeSwapCore };
import type * as fileBridgeSwapPeriphery from "./file_bridge_swap_periphery";
export type { fileBridgeSwapPeriphery };
export type { MainBridge } from "./MainBridge";
export type { ProxyBridge } from "./ProxyBridge";
