/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridgeProxySol from "./BridgeProxy.sol";
export type { bridgeProxySol };
import type * as daiSol from "./DAI.sol";
export type { daiSol };
import type * as fdaiSol from "./FDAI.sol";
export type { fdaiSol };
