/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface FileBridgeInterface extends utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "GOVERNANCE_ROLE()": FunctionFragment;
    "WFIL_ADDRESS()": FunctionFragment;
    "addWToken(address,address)": FunctionFragment;
    "bridgeVersion()": FunctionFragment;
    "chainGasAmount()": FunctionFragment;
    "changeWToken(address,address)": FunctionFragment;
    "depositToken(address,uint256,address,uint256)": FunctionFragment;
    "getFeeBalance(address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "redeemToken(address,uint256,address,uint256)": FunctionFragment;
    "redeemV2(bytes32,uint256,address,uint256)": FunctionFragment;
    "removeWToken(address)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setChainGasAmount(uint256)": FunctionFragment;
    "setWethAddress(address)": FunctionFragment;
    "startBlockNumber()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "tokenToWTokenMap(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "withdrawFees(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNANCE_ROLE"
      | "WFIL_ADDRESS"
      | "addWToken"
      | "bridgeVersion"
      | "chainGasAmount"
      | "changeWToken"
      | "depositToken"
      | "getFeeBalance"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "pause"
      | "paused"
      | "redeemToken"
      | "redeemV2"
      | "removeWToken"
      | "renounceRole"
      | "revokeRole"
      | "setChainGasAmount"
      | "setWethAddress"
      | "startBlockNumber"
      | "supportsInterface"
      | "tokenToWTokenMap"
      | "unpause"
      | "withdrawFees"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WFIL_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addWToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chainGasAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeWToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeBalance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemV2",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setChainGasAmount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWethAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "startBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToWTokenMap",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WFIL_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addWToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chainGasAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeWToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeemV2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeWToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setChainGasAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWethAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenToWTokenMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "Paused(address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "TokenAddedToList(address,address)": EventFragment;
    "TokenChangedInList(address,address,address)": EventFragment;
    "TokenDeposit(address,uint256,address,uint256)": EventFragment;
    "TokenDepositAndSwap(address,uint256,address,uint256,uint8,uint8,uint256,uint256)": EventFragment;
    "TokenMint(address,address,uint256,uint256,bytes32)": EventFragment;
    "TokenMintAndSwap(address,address,uint256,uint256,uint8,uint8,uint256,uint256,bool,bytes32)": EventFragment;
    "TokenRedeem(address,uint256,address,uint256)": EventFragment;
    "TokenRedeemAndRemove(address,uint256,address,uint256,uint8,uint256,uint256)": EventFragment;
    "TokenRedeemAndSwap(address,uint256,address,uint256,uint8,uint8,uint256,uint256)": EventFragment;
    "TokenRedeemV2(bytes32,uint256,address,uint256)": EventFragment;
    "TokenRemovedFromList(address)": EventFragment;
    "TokenWithdraw(address,address,uint256,uint256,bytes32)": EventFragment;
    "TokenWithdrawAndRemove(address,address,uint256,uint256,uint8,uint256,uint256,bool,bytes32)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenAddedToList"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenChangedInList"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenDepositAndSwap"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenMint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenMintAndSwap"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRedeem"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRedeemAndRemove"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRedeemAndSwap"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRedeemV2"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRemovedFromList"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWithdrawAndRemove"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface TokenAddedToListEventObject {
  _token: string;
  _WToken: string;
}
export type TokenAddedToListEvent = TypedEvent<
  [string, string],
  TokenAddedToListEventObject
>;

export type TokenAddedToListEventFilter =
  TypedEventFilter<TokenAddedToListEvent>;

export interface TokenChangedInListEventObject {
  _token: string;
  _WTokenOld: string;
  _WTokenNew: string;
}
export type TokenChangedInListEvent = TypedEvent<
  [string, string, string],
  TokenChangedInListEventObject
>;

export type TokenChangedInListEventFilter =
  TypedEventFilter<TokenChangedInListEvent>;

export interface TokenDepositEventObject {
  to: string;
  chainId: BigNumber;
  token: string;
  amount: BigNumber;
}
export type TokenDepositEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  TokenDepositEventObject
>;

export type TokenDepositEventFilter = TypedEventFilter<TokenDepositEvent>;

export interface TokenDepositAndSwapEventObject {
  to: string;
  chainId: BigNumber;
  token: string;
  amount: BigNumber;
  tokenIndexFrom: number;
  tokenIndexTo: number;
  minDy: BigNumber;
  deadline: BigNumber;
}
export type TokenDepositAndSwapEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, number, number, BigNumber, BigNumber],
  TokenDepositAndSwapEventObject
>;

export type TokenDepositAndSwapEventFilter =
  TypedEventFilter<TokenDepositAndSwapEvent>;

export interface TokenMintEventObject {
  to: string;
  token: string;
  amount: BigNumber;
  fee: BigNumber;
  kappa: string;
}
export type TokenMintEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string],
  TokenMintEventObject
>;

export type TokenMintEventFilter = TypedEventFilter<TokenMintEvent>;

export interface TokenMintAndSwapEventObject {
  to: string;
  token: string;
  amount: BigNumber;
  fee: BigNumber;
  tokenIndexFrom: number;
  tokenIndexTo: number;
  minDy: BigNumber;
  deadline: BigNumber;
  swapSuccess: boolean;
  kappa: string;
}
export type TokenMintAndSwapEvent = TypedEvent<
  [
    string,
    string,
    BigNumber,
    BigNumber,
    number,
    number,
    BigNumber,
    BigNumber,
    boolean,
    string
  ],
  TokenMintAndSwapEventObject
>;

export type TokenMintAndSwapEventFilter =
  TypedEventFilter<TokenMintAndSwapEvent>;

export interface TokenRedeemEventObject {
  to: string;
  chainId: BigNumber;
  token: string;
  amount: BigNumber;
}
export type TokenRedeemEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  TokenRedeemEventObject
>;

export type TokenRedeemEventFilter = TypedEventFilter<TokenRedeemEvent>;

export interface TokenRedeemAndRemoveEventObject {
  to: string;
  chainId: BigNumber;
  token: string;
  amount: BigNumber;
  swapTokenIndex: number;
  swapMinAmount: BigNumber;
  swapDeadline: BigNumber;
}
export type TokenRedeemAndRemoveEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, number, BigNumber, BigNumber],
  TokenRedeemAndRemoveEventObject
>;

export type TokenRedeemAndRemoveEventFilter =
  TypedEventFilter<TokenRedeemAndRemoveEvent>;

export interface TokenRedeemAndSwapEventObject {
  to: string;
  chainId: BigNumber;
  token: string;
  amount: BigNumber;
  tokenIndexFrom: number;
  tokenIndexTo: number;
  minDy: BigNumber;
  deadline: BigNumber;
}
export type TokenRedeemAndSwapEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, number, number, BigNumber, BigNumber],
  TokenRedeemAndSwapEventObject
>;

export type TokenRedeemAndSwapEventFilter =
  TypedEventFilter<TokenRedeemAndSwapEvent>;

export interface TokenRedeemV2EventObject {
  to: string;
  chainId: BigNumber;
  token: string;
  amount: BigNumber;
}
export type TokenRedeemV2Event = TypedEvent<
  [string, BigNumber, string, BigNumber],
  TokenRedeemV2EventObject
>;

export type TokenRedeemV2EventFilter = TypedEventFilter<TokenRedeemV2Event>;

export interface TokenRemovedFromListEventObject {
  _token: string;
}
export type TokenRemovedFromListEvent = TypedEvent<
  [string],
  TokenRemovedFromListEventObject
>;

export type TokenRemovedFromListEventFilter =
  TypedEventFilter<TokenRemovedFromListEvent>;

export interface TokenWithdrawEventObject {
  to: string;
  token: string;
  amount: BigNumber;
  fee: BigNumber;
  kappa: string;
}
export type TokenWithdrawEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string],
  TokenWithdrawEventObject
>;

export type TokenWithdrawEventFilter = TypedEventFilter<TokenWithdrawEvent>;

export interface TokenWithdrawAndRemoveEventObject {
  to: string;
  token: string;
  amount: BigNumber;
  fee: BigNumber;
  swapTokenIndex: number;
  swapMinAmount: BigNumber;
  swapDeadline: BigNumber;
  swapSuccess: boolean;
  kappa: string;
}
export type TokenWithdrawAndRemoveEvent = TypedEvent<
  [
    string,
    string,
    BigNumber,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    boolean,
    string
  ],
  TokenWithdrawAndRemoveEventObject
>;

export type TokenWithdrawAndRemoveEventFilter =
  TypedEventFilter<TokenWithdrawAndRemoveEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface FileBridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FileBridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    GOVERNANCE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    WFIL_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    addWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bridgeVersion(overrides?: CallOverrides): Promise<[BigNumber]>;

    chainGasAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    changeWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getFeeBalance(
      tokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    redeemToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeemV2(
      to: PromiseOrValue<BytesLike>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeWToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setChainGasAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWethAddress(
      _wethAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startBlockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tokenToWTokenMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFees(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  GOVERNANCE_ROLE(overrides?: CallOverrides): Promise<string>;

  WFIL_ADDRESS(overrides?: CallOverrides): Promise<string>;

  addWToken(
    _token: PromiseOrValue<string>,
    _fToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bridgeVersion(overrides?: CallOverrides): Promise<BigNumber>;

  chainGasAmount(overrides?: CallOverrides): Promise<BigNumber>;

  changeWToken(
    _token: PromiseOrValue<string>,
    _fToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositToken(
    to: PromiseOrValue<string>,
    chainId: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getFeeBalance(
    tokenAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  redeemToken(
    to: PromiseOrValue<string>,
    chainId: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeemV2(
    to: PromiseOrValue<BytesLike>,
    chainId: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeWToken(
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setChainGasAmount(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWethAddress(
    _wethAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tokenToWTokenMap(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFees(
    token: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    GOVERNANCE_ROLE(overrides?: CallOverrides): Promise<string>;

    WFIL_ADDRESS(overrides?: CallOverrides): Promise<string>;

    addWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgeVersion(overrides?: CallOverrides): Promise<BigNumber>;

    chainGasAmount(overrides?: CallOverrides): Promise<BigNumber>;

    changeWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getFeeBalance(
      tokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(overrides?: CallOverrides): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    redeemToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    redeemV2(
      to: PromiseOrValue<BytesLike>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeWToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setChainGasAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWethAddress(
      _wethAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    startBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tokenToWTokenMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    unpause(overrides?: CallOverrides): Promise<void>;

    withdrawFees(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "TokenAddedToList(address,address)"(
      _token?: null,
      _WToken?: null
    ): TokenAddedToListEventFilter;
    TokenAddedToList(
      _token?: null,
      _WToken?: null
    ): TokenAddedToListEventFilter;

    "TokenChangedInList(address,address,address)"(
      _token?: null,
      _WTokenOld?: null,
      _WTokenNew?: null
    ): TokenChangedInListEventFilter;
    TokenChangedInList(
      _token?: null,
      _WTokenOld?: null,
      _WTokenNew?: null
    ): TokenChangedInListEventFilter;

    "TokenDeposit(address,uint256,address,uint256)"(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null
    ): TokenDepositEventFilter;
    TokenDeposit(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null
    ): TokenDepositEventFilter;

    "TokenDepositAndSwap(address,uint256,address,uint256,uint8,uint8,uint256,uint256)"(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null,
      tokenIndexFrom?: null,
      tokenIndexTo?: null,
      minDy?: null,
      deadline?: null
    ): TokenDepositAndSwapEventFilter;
    TokenDepositAndSwap(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null,
      tokenIndexFrom?: null,
      tokenIndexTo?: null,
      minDy?: null,
      deadline?: null
    ): TokenDepositAndSwapEventFilter;

    "TokenMint(address,address,uint256,uint256,bytes32)"(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenMintEventFilter;
    TokenMint(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenMintEventFilter;

    "TokenMintAndSwap(address,address,uint256,uint256,uint8,uint8,uint256,uint256,bool,bytes32)"(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      tokenIndexFrom?: null,
      tokenIndexTo?: null,
      minDy?: null,
      deadline?: null,
      swapSuccess?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenMintAndSwapEventFilter;
    TokenMintAndSwap(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      tokenIndexFrom?: null,
      tokenIndexTo?: null,
      minDy?: null,
      deadline?: null,
      swapSuccess?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenMintAndSwapEventFilter;

    "TokenRedeem(address,uint256,address,uint256)"(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null
    ): TokenRedeemEventFilter;
    TokenRedeem(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null
    ): TokenRedeemEventFilter;

    "TokenRedeemAndRemove(address,uint256,address,uint256,uint8,uint256,uint256)"(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null,
      swapTokenIndex?: null,
      swapMinAmount?: null,
      swapDeadline?: null
    ): TokenRedeemAndRemoveEventFilter;
    TokenRedeemAndRemove(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null,
      swapTokenIndex?: null,
      swapMinAmount?: null,
      swapDeadline?: null
    ): TokenRedeemAndRemoveEventFilter;

    "TokenRedeemAndSwap(address,uint256,address,uint256,uint8,uint8,uint256,uint256)"(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null,
      tokenIndexFrom?: null,
      tokenIndexTo?: null,
      minDy?: null,
      deadline?: null
    ): TokenRedeemAndSwapEventFilter;
    TokenRedeemAndSwap(
      to?: PromiseOrValue<string> | null,
      chainId?: null,
      token?: null,
      amount?: null,
      tokenIndexFrom?: null,
      tokenIndexTo?: null,
      minDy?: null,
      deadline?: null
    ): TokenRedeemAndSwapEventFilter;

    "TokenRedeemV2(bytes32,uint256,address,uint256)"(
      to?: PromiseOrValue<BytesLike> | null,
      chainId?: null,
      token?: null,
      amount?: null
    ): TokenRedeemV2EventFilter;
    TokenRedeemV2(
      to?: PromiseOrValue<BytesLike> | null,
      chainId?: null,
      token?: null,
      amount?: null
    ): TokenRedeemV2EventFilter;

    "TokenRemovedFromList(address)"(
      _token?: null
    ): TokenRemovedFromListEventFilter;
    TokenRemovedFromList(_token?: null): TokenRemovedFromListEventFilter;

    "TokenWithdraw(address,address,uint256,uint256,bytes32)"(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenWithdrawEventFilter;
    TokenWithdraw(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenWithdrawEventFilter;

    "TokenWithdrawAndRemove(address,address,uint256,uint256,uint8,uint256,uint256,bool,bytes32)"(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      swapTokenIndex?: null,
      swapMinAmount?: null,
      swapDeadline?: null,
      swapSuccess?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenWithdrawAndRemoveEventFilter;
    TokenWithdrawAndRemove(
      to?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null,
      fee?: null,
      swapTokenIndex?: null,
      swapMinAmount?: null,
      swapDeadline?: null,
      swapSuccess?: null,
      kappa?: PromiseOrValue<BytesLike> | null
    ): TokenWithdrawAndRemoveEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    GOVERNANCE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    WFIL_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    addWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bridgeVersion(overrides?: CallOverrides): Promise<BigNumber>;

    chainGasAmount(overrides?: CallOverrides): Promise<BigNumber>;

    changeWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getFeeBalance(
      tokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    redeemToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeemV2(
      to: PromiseOrValue<BytesLike>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeWToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setChainGasAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWethAddress(
      _wethAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenToWTokenMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFees(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GOVERNANCE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WFIL_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bridgeVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chainGasAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeWToken(
      _token: PromiseOrValue<string>,
      _fToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getFeeBalance(
      tokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeemToken(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeemV2(
      to: PromiseOrValue<BytesLike>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeWToken(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setChainGasAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWethAddress(
      _wethAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startBlockNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenToWTokenMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFees(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
