/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factorySol from "./factory.sol";
export type { factorySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { FileswapV2ERC20 } from "./FileswapV2ERC20";
export type { FileswapV2Pair } from "./FileswapV2Pair";
