/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFileswapV1Exchange } from "./IFileswapV1Exchange";
export type { IFileswapV1Factory } from "./IFileswapV1Factory";
