/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v1 from "./V1";
export type { v1 };
export type { IERC20 } from "./IERC20";
export type { IFileswapV2Migrator } from "./IFileswapV2Migrator";
export type { IFileswapV2Router01 } from "./IFileswapV2Router01";
export type { IFileswapV2Router02 } from "./IFileswapV2Router02";
export type { IWETH } from "./IWETH";
