/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFileswapV2Migrator,
  IFileswapV2MigratorInterface,
} from "../../../../contracts/file_bridge_swap_periphery/interfaces/IFileswapV2Migrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenMin",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETHMin",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFileswapV2Migrator__factory {
  static readonly abi = _abi;
  static createInterface(): IFileswapV2MigratorInterface {
    return new utils.Interface(_abi) as IFileswapV2MigratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFileswapV2Migrator {
    return new Contract(address, _abi, signerOrProvider) as IFileswapV2Migrator;
  }
}
