/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bridgeProxySol from "./BridgeProxy.sol";
export * as daiSol from "./DAI.sol";
export * as fdaiSol from "./FDAI.sol";
