/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  MainBridge,
  MainBridgeInterface,
} from "../../contracts/MainBridge";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "requester",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TokensLocked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "requester",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TokensUnlocked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_requester",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "lockTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_requester",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "unlockTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061017e806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80639d564d9a1461003b578063b1c2558614610050575b600080fd5b61004e610049366004610103565b610063565b005b61004e61005e366004610103565b6100b7565b6040805173ffffffffffffffffffffffffffffffffffffffff84168152602081018390527fe7b379c6c1fa169e9079c25e9143b127637eef8ec8c9d5c06ddb4ab3e119588891015b60405180910390a15050565b6040805173ffffffffffffffffffffffffffffffffffffffff84168152602081018390527fac87f20a77d28ee8bbb58ec87ea8fa968b3393efae1a368fd50b767c2847391c91016100ab565b6000806040838503121561011657600080fd5b823573ffffffffffffffffffffffffffffffffffffffff8116811461013a57600080fd5b94602093909301359350505056fea26469706673582212204a8229d0f8bc51383be043f05b71c493796fa19b33ea68d16553227cf7d6bd0664736f6c634300080a0033";

type MainBridgeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MainBridgeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MainBridge__factory extends ContractFactory {
  constructor(...args: MainBridgeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MainBridge> {
    return super.deploy(overrides || {}) as Promise<MainBridge>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MainBridge {
    return super.attach(address) as MainBridge;
  }
  override connect(signer: Signer): MainBridge__factory {
    return super.connect(signer) as MainBridge__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MainBridgeInterface {
    return new utils.Interface(_abi) as MainBridgeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MainBridge {
    return new Contract(address, _abi, signerOrProvider) as MainBridge;
  }
}
