/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iFileswaV2Erc20Sol from "./IFileswaV2ERC20.sol";
export type { iFileswaV2Erc20Sol };
export type { IERC20 } from "./IERC20";
export type { IFileswapV2Callee } from "./IFileswapV2Callee";
export type { IFileswapV2ERC20 } from "./IFileswapV2ERC20";
export type { IFileswapV2Factory } from "./IFileswapV2Factory";
export type { IFileswapV2Pair } from "./IFileswapV2Pair";
