/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fileBridgeSol from "./FileBridge.sol";
export type { fileBridgeSol };
import type * as nodeManagerSol from "./NodeManager.sol";
export type { nodeManagerSol };
