/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { FileswapV2ERC20__factory } from "./FileswapV2ERC20__factory";
export { FileswapV2Factory__factory } from "./FileswapV2Factory__factory";
export { FileswapV2Pair__factory } from "./FileswapV2Pair__factory";
